name = "mission-worker"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MissionState", "FleetState"]

[[durable_objects.bindings]]
name = "MISSION_STATE"
class_name = "MissionState"

[[services]]
binding = "icc-pivot-engine"
service = "icc-pivot-engine"

[[services]]
binding = "mission-comms"
service = "mission-comms"